fix

diff --git a/.github/workflows/build auto.yml b/.github/workflows/build auto.yml
--- a/.github/workflows/build auto.yml
+++ b/.github/workflows/build auto.yml
@@ -71,7 +71,7 @@ jobs:
             CertificateRsa1=$(xmlstarlet sel -t -v "//Key[@algorithm='rsa']/CertificateChain/Certificate[1]" "$XML_FILE")
             CertificateRsa2=$(xmlstarlet sel -t -v "//Key[@algorithm='rsa']/CertificateChain/Certificate[2]" "$XML_FILE")
             CertificateRsa3=$(xmlstarlet sel -t -v "//Key[@algorithm='rsa']/CertificateChain/Certificate[3]" "$XML_FILE")
-            
+
             # Lấy tên cơ sở của tệp XML
             base_name_xml=$(basename "$XML_FILE" .xml)
             echo "File: $base_name_xml"
@@ -80,31 +80,32 @@ jobs:
             # echo "PrivateKey (ECDSA): $PrivateKeyEcdsa"
             # echo "PrivateKey (RSA): $PrivateKeyRsa"
             # Thay thế nội dung và xây dựng ứng dụng
-            sed -e 's/PLACEHOLDER_EC_PRIVATE_KEY/$PrivateKeyEcdsa/g' \
-              -e 's/PLACEHOLDER_RSA_PRIVATE_KEY/$PrivateKeyRsa/g' \
-              -e 's/PLACEHOLDER_EC_CERTIFICATE_1/$CertificateEcdsa1/g' \
-              -e 's/PLACEHOLDER_EC_CERTIFICATE_2/$CertificateEcdsa2/g' \
-              -e 's/PLACEHOLDER_EC_CERTIFICATE_3/$CertificateEcdsa3/g' \
-              -e 's/PLACEHOLDER_RSA_CERTIFICATE_1/$CertificateRsa1/g' \
-              -e 's/PLACEHOLDER_RSA_CERTIFICATE_2/$CertificateRsa2/g' \
-              -e 's/PLACEHOLDER_RSA_CERTIFICATE_3/$CertificateRsa3/g' \
-              Keybox_template.java > app/src/main/java/com/android/internal/util/framework/Keybox.java
-            
+
+            keybox=app/src/main/java/com/android/internal/util/framework/Keybox.java
+            cp -f my_files/Keybox_template.java $keybox
+            awk -v key="$PrivateKeyEcdsa" '{gsub(/^\s*PLACEHOLDER_EC_PRIVATE_KEY/, key); print}' "$keybox" >temp && mv temp "$keybox"
+            awk -v key="$CertificateEcdsa1" '{gsub(/^\s*PLACEHOLDER_EC_CERTIFICATE_1/, key); print}' "$keybox" >temp && mv temp "$keybox"
+            awk -v key="$CertificateEcdsa2" '{gsub(/^\s*PLACEHOLDER_EC_CERTIFICATE_2/, key); print}' "$keybox" >temp && mv temp "$keybox"
+            awk -v key="$CertificateEcdsa3" '{gsub(/^\s*PLACEHOLDER_EC_CERTIFICATE_3/, key); print}' "$keybox" >temp && mv temp "$keybox"
+            awk -v key="$PrivateKeyRsa" '{gsub(/^\s*PLACEHOLDER_RSA_PRIVATE_KEY/, key); print}' "$keybox" >temp && mv temp "$keybox"
+            awk -v key="$CertificateRsa1" '{gsub(/^\s*PLACEHOLDER_RSA_CERTIFICATE_1/, key); print}' "$keybox" >temp && mv temp "$keybox"
+            awk -v key="$CertificateRsa2" '{gsub(/^\s*PLACEHOLDER_RSA_CERTIFICATE_2/, key); print}' "$keybox" >temp && mv temp "$keybox"
+            awk -v key="$CertificateRsa3" '{gsub(/^\s*PLACEHOLDER_RSA_CERTIFICATE_3/, key); print}' "$keybox" >temp && mv temp "$keybox"
             echo "Đã thay thế!!"
             # Chạy Gradle
             ./gradlew clean assembleRelease >/dev/null 2>&1
-            
+
             # Kiểm tra và sao chép tệp dex
             DexFile=$(find app/build/intermediates/dex/release/ -name 'classes.dex')
             if [ -z "$DexFile" ]; then
-              echo "Error: No dex file found."
-              exit 1
+                echo "Error: No dex file found."
+                exit 1
             fi
-            
+
             # Sao chép tệp dex vào thư mục out
             mkdir -p outdex
             sudo mv "$DexFile" outdex/"$base_name_xml".dex
-          done
+        done
 
       - name: Uploading release
         uses: softprops/action-gh-release@v2
