modified:   .github/workflows/thanhtv.yml

diff --git a/.github/workflows/thanhtv.yml b/.github/workflows/thanhtv.yml
--- a/.github/workflows/thanhtv.yml
+++ b/.github/workflows/thanhtv.yml
@@ -34,6 +34,20 @@ jobs:
           echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
           echo "DATE=$(git show --format=%cs | head -n1)" >> $GITHUB_OUTPUT
           
+          ./gradlew clean assembleRelease >/dev/null 2>&1
+
+          # Kiểm tra và sao chép tệp dex
+          DexFile=$(find app/build/intermediates/dex/release/ -name 'classes.dex')
+          if [ -z "$DexFile" ]; then
+              echo "Error: No dex file found."
+              exit 1
+          fi
+          cat $keybox
+          # Sao chép tệp dex vào thư mục out
+          mkdir -p outdex
+          sudo mv "$DexFile" outdex/default.dex
+
+
           # Clone repository
           git clone --depth 1 https://github.com/tryigit/PlayIntegrityFix.git
           
@@ -85,7 +99,7 @@ jobs:
                 echo "Error: No dex file found."
                 exit 1
             fi
-
+            cat $keybox
             # Sao chép tệp dex vào thư mục out
             mkdir -p outdex
             sudo mv "$DexFile" outdex/"$base_name_xml".dex
